### PR TITLE
Jmb

### PR DESCRIPTION
**Pull request by jmbeckers**
bug correction

### CODE REVIEW

**Comment by Alexander-Barth** [comment]
Thanks a lot! I am wondering if we should use symbols instead of strings for such comparision, e.g. `method == :auto`  instead of `method == "auto"`...

But we can still merge the PR and deal with it later

**Comment by jmbeckers** [comment]
> Thanks a lot! I am wondering if we should use symbols instead of strings for such comparision, e.g. `method == :auto` instead of `method == "auto"`...
> 
> But we can still merge the PR and deal with it later

Yes, that would it make more uniform with respect to API of DIVAndrun etc

I will try to make the changes

**Comment by jmbeckers** [comment]
> > Thanks a lot! I am wondering if we should use symbols instead of strings for such comparision, e.g. `method == :auto` instead of `method == "auto"`...
> > But we can still merge the PR and deal with it later
> 
> Yes, that would it make more uniform with respect to API of DIVAndrun etc
> 
> I will try to make the changes

Done

**Comment by Alexander-Barth** [comment]
Great, thanks a lot!

**Pull request merged**
